<template>
  <div class="hot-page">
    <section class="hot-hero"><div class="trove-container hot-hero-grid"><div><span class="section-kicker">Горящие предложения</span><h1>Хороший отпуск<br /><em>иногда находится внезапно.</em></h1><p>Мы собираем предложения с заметным снижением цены и показываем их без лишнего шума.</p><NuxtLink to="/tours" class="trove-button trove-button--brand">Найти свой тур <ArrowRight :size="18" /></NuxtLink></div><div class="hero-image"><img src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85" alt="Пляж" @error="fallbackImage" /><div class="hero-note"><Flame :size="16" /><div><b>Обновляем цены</b><small>и наличие предложений</small></div></div></div></div></section>
    <section class="page-section"><div class="trove-container"><div class="section-head"><div><span class="section-kicker">Сегодня</span><h2 class="section-title">Предложения с хорошей ценой</h2><p class="section-lead">Сравнивайте их так же, как обычные туры: рейтинг, питание, перелёт и итоговая цена рядом.</p></div><span class="updated">Обновлено только что</span></div><div class="cards"><TourCard v-for="tour in hotTours" :key="tour.id" :tour="tour" /></div></div></section>
    <section class="trove-container hot-tip"><div><span class="section-kicker">Полезно знать</span><h2>Цена может измениться.</h2><p>Поэтому Trove повторно проверяет предложение перед бронированием. Если цена изменилась, мы покажем это до оплаты.</p></div><NuxtLink to="/tours" class="trove-button trove-button--light">Смотреть все туры <ArrowRight :size="17" /></NuxtLink></section>
  </div>
</template>
<script setup lang="ts">
import { ArrowRight, Flame } from '@lucide/vue'
import TourCard from '@entities/tours/ui/cards/TourCard.vue'
import { useTours } from '@composables/useTours'
const { hotTours } = useTours()
const fallback='/images/trove-landscape.svg'
const fallbackImage=(event:Event)=>{const image=event.target as HTMLImageElement;if(image.src!==fallback)image.src=fallback}
</script>
<style scoped lang="scss">
.hot-hero{background:#eef2ee;border-bottom:1px solid var(--line);padding:58px 0 46px}.hot-hero-grid{display:grid;grid-template-columns:1fr .88fr;gap:54px;align-items:center}.hot-hero h1{margin:14px 0 18px;font-family:var(--font-display);font-size:clamp(48px,5.5vw,74px);line-height:.98;font-weight:800;letter-spacing:-.06em}.hot-hero h1 em{font-style:normal;color:var(--brand)}.hot-hero p{max-width:610px;margin:0 0 25px;color:var(--ink-2);font-size:17px;line-height:1.65}.hero-image{position:relative;height:410px;overflow:hidden;border-radius:22px}.hero-image img{width:100%;height:100%;display:block;object-fit:cover}.hero-note{position:absolute;left:16px;bottom:16px;display:flex;align-items:center;gap:8px;padding:11px 13px;background:#fff;border:1px solid var(--line);border-radius:11px;box-shadow:var(--shadow-md)}.hero-note svg{color:var(--brand)}.hero-note b,.hero-note small{display:block}.hero-note b{font-size:12px}.hero-note small{margin-top:2px;color:var(--muted);font-size:10px}.updated{color:var(--muted);font-size:12px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.hot-tip{display:flex;align-items:center;justify-content:space-between;gap:40px;margin-bottom:58px;padding:38px 42px;background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow-sm)}.hot-tip h2{margin:7px 0 7px;font-family:var(--font-display);font-size:36px;letter-spacing:-.04em}.hot-tip p{max-width:680px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}@media(max-width:900px){.hot-hero-grid{grid-template-columns:1fr}.cards{grid-template-columns:1fr 1fr}.hot-tip{display:block}}@media(max-width:620px){.hot-hero{padding:45px 0}.hot-hero h1{font-size:49px}.hero-image{height:300px}.cards{grid-template-columns:1fr}.hot-tip{padding:30px;margin-inline:16px}.hot-tip h2{font-size:32px}.hot-tip .trove-button{margin-top:20px;width:100%}}
</style>
