<template>
  <main v-if="article" class="article-page">
    <div class="trove-container">
      <nav class="breadcrumbs" aria-label="Хлебные крошки"><NuxtLink to="/" class="crumb-back"><ArrowLeft :size="14" /> Главная</NuxtLink><ChevronRight :size="14" class="crumb-separator" /><NuxtLink to="/guides">Trove Гид</NuxtLink><ChevronRight :size="14" class="crumb-separator" /><strong>{{ article.title }}</strong></nav>
      <article>
        <header class="article-head"><span class="section-kicker">{{ article.tag }} · {{ article.time }}</span><h1>{{ article.title }}</h1><p>{{ article.intro }}</p><div class="meta"><span><CalendarDays :size="15" /> Обновлено сегодня</span><span><Clock3 :size="15" /> {{ article.time }} чтения</span></div></header>
        <figure class="cover"><img :src="article.image" :alt="article.title" @error="fallbackImage" /><figcaption>{{ article.caption }}</figcaption></figure>
        <div class="article-layout">
          <aside class="toc"><span>В статье</span><a v-for="item in article.sections" :key="item.id" :href="`#${item.id}`">{{ item.heading }}</a></aside>
          <div class="prose"><section v-for="section in article.sections" :id="section.id" :key="section.id"><h2>{{ section.heading }}</h2><p v-for="paragraph in section.text" :key="paragraph">{{ paragraph }}</p></section><div class="article-cta"><div><span class="section-kicker">Готовы ехать?</span><h2>Посмотреть туры по направлению</h2><p>Trove сравнит предложения и покажет цену до бронирования.</p></div><NuxtLink to="/tours" class="trove-button trove-button--brand">Найти тур <ArrowRight :size="17" /></NuxtLink></div></div>
        </div>
      </article>
    </div>
  </main>
  <main v-else class="not-found"><div>⌕</div><h1>Материал не найден</h1><p>Вернитесь в Trove Гид и выберите другую статью.</p><NuxtLink to="/guides" class="trove-button trove-button--brand">Открыть гид</NuxtLink></main>
</template>
<script setup lang="ts">
import { ArrowRight, CalendarDays, ChevronRight, Clock3 } from '@lucide/vue'
import { useApi } from '../../../composables/useApi';
const route=useRoute()
const fallback='/images/trove-landscape.svg'
const fallbackImage=(event:Event)=>{const image=event.target as HTMLImageElement;if(image.src!==fallback)image.src=fallback}
const articles= {
  'warm-sea-autumn': {tag:'Направления',time:'7 мин',title:'Куда поехать за тёплым морем осенью?',intro:'Как выбрать направление по погоде, перелёту и формату отдыха — без попытки объехать всё побережье за неделю.',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88',caption:'Тёплое море — хороший повод не заканчивать сезон слишком рано.',sections:[{id:'weather',heading:'Сначала смотрите на сезон',text:['Осенью одно и то же направление может ощущаться совершенно по-разному. Сравнивайте среднюю температуру воздуха и воды, продолжительность светового дня и вероятность дождей.','Если важен именно пляжный отдых, выбирайте даты с запасом, а не только самый дешёвый тариф.']},{id:'region',heading:'Регион важнее названия страны',text:['Внутри одной страны климат, пляжи и атмосфера могут сильно отличаться. Сначала определите желаемый ритм отдыха — спокойный курорт, город у моря или активные поездки.','После этого уже сравнивайте конкретные отели и перелёты. Так фильтры становятся полезнее, а выбор — заметно быстрее.']},{id:'price',heading:'Сравнивайте итоговую цену',text:['Смотрите на стоимость всей поездки: перелёт, питание, багаж и трансфер. Очень низкая цена в выдаче не всегда означает низкую цену на финальном шаге.','Trove повторно проверяет доступность предложения перед бронированием, поэтому изменение цены не должно быть неожиданностью.']}]},
  'istanbul-five-days': {tag:'Города',time:'5 мин',title:'Стамбул на пять дней без гонки',intro:'Маршрут для тех, кто хочет увидеть город, но оставить время на кофе, Босфор и обычные прогулки.',image:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1600&q=88',caption:'Стамбул хорошо работает, когда маршрут оставляет место для спонтанных остановок.',sections:[{id:'districts',heading:'Выберите удобный район',text:['Для короткой поездки особенно важна логистика. Лучше жить там, откуда удобно добираться до нескольких ключевых районов без ежедневных длинных переездов.']},{id:'days',heading:'Оставьте один день свободным',text:['Первые несколько дней можно посвятить историческому центру и Босфору, а один день оставить без плотного плана. Это помогает почувствовать город, а не просто закрыть список достопримечательностей.']},{id:'food',heading:'Еда — часть маршрута',text:['В Стамбуле кафе и рынки сами по себе становятся точками маршрута. Закладывайте время на остановки, особенно если путешествуете не в одиночку.']}]},
  'dubai-without-rush': {tag:'Города',time:'5 мин',title:'Дубай без гонки за достопримечательностями',intro:'Как совместить море, город и пару красивых вечеров, не превращая отпуск в марафон.',image:'https://images.unsplash.com/photo-1642577784769-527a61364162?auto=format&fit=crop&w=1600&q=88',caption:'Дубай можно смотреть в своём ритме — между пляжем, городом и спокойными вечерами.',sections:[{id:'rhythm',heading:'Не пытайтесь увидеть всё',text:['Для короткой поездки лучше выбрать несколько зон и оставить между ними запас времени. Так день не превращается в последовательность трансферов и очередей.']},{id:'areas',heading:'Соберите маршрут по районам',text:['Объединяйте точки по географии: утром город, днём пляж или район рядом, вечером ресторан неподалёку. Такой подход даёт больше времени на сам отдых.']},{id:'hotel',heading:'Отель выбирайте под сценарий',text:['Если важен пляж, смотрите на реальное расстояние до берега. Если планируете много городских прогулок, удобный транспорт и расположение могут быть важнее вида из окна.']}]},
  'choose-hotel': {tag:'Советы',time:'6 мин',title:'Как выбрать отель и не пожалеть',intro:'Звёзды и фотографии — только начало. Вот какие параметры стоит сравнить перед бронированием.',image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=88',caption:'Хороший отель — это не только красивая фотография номера.',sections:[{id:'location',heading:'Локация',text:['Проверьте время до пляжа, центра и транспорта, а не только название района. Для короткого отдыха несколько лишних пересадок каждый день быстро становятся заметными.']},{id:'reviews',heading:'Читайте отзывы по теме',text:['Ищите повторяющиеся наблюдения: шум, уборка, завтрак, пляж, состояние номеров. Один эмоциональный отзыв полезнее воспринимать как сигнал, а не как окончательный вывод.']},{id:'meal',heading:'Сравнивайте питание',text:['All inclusive, завтраки и полный пансион имеют разную ценность в зависимости от формата поездки. Сопоставляйте питание с планами на день и итоговой ценой тура.']}]}
} as const
const staticArticle=computed(()=>articles[String(route.params.slug) as keyof typeof articles])
const api=useApi()
const remoteArticle=ref<any>(null)
try {
  const response=await api<{item:any}>(`/api/guides/${route.params.slug}`)
  remoteArticle.value=response.item
} catch {}
const article=computed(()=>{
  if (!remoteArticle.value) return staticArticle.value
  const item=remoteArticle.value
  const paragraphs=String(item.content||'').split(/\n\s*\n/).map((x:string)=>x.trim()).filter(Boolean)
  return {tag:'Trove Гид',time:'6 мин',title:item.title,intro:item.excerpt||'',image:item.cover_url||fallback,caption:'Материал Trove Гид.',sections:paragraphs.length?[{id:'content',heading:'Материал',text:paragraphs}]:[]}
})
</script>
<style scoped lang="scss">
.article-page{padding:20px 0 96px}.breadcrumbs{display:flex;align-items:center;gap:8px;min-height:40px;padding:0 2px;color:var(--muted);font-size:12px}.crumb-back{display:inline-flex;align-items:center;gap:6px;padding:8px 10px;border:1px solid var(--line);border-radius:10px;background:var(--paper);font-weight:800}.crumb-separator{color:var(--muted-2)}.breadcrumbs a{color:var(--muted)!important;text-decoration:none!important}.breadcrumbs strong{max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ink)}.article-head{max-width:900px;padding:64px 0 34px}.article-head h1{margin:12px 0 15px;font-family:var(--font-display);font-size:clamp(44px,6vw,76px);line-height:.97;letter-spacing:-.065em}.article-head>p{max-width:720px;margin:0;color:var(--ink-2);font-size:18px;line-height:1.65}.meta{display:flex;gap:18px;margin-top:20px;color:var(--muted);font-size:11px}.meta span{display:inline-flex;align-items:center;gap:6px}.cover{margin:0}.cover img{width:100%;height:min(58vw,620px);display:block;object-fit:cover;border-radius:24px}.cover figcaption{margin-top:8px;color:var(--muted);font-size:11px}.article-layout{display:grid;grid-template-columns:190px minmax(0,760px);gap:70px;justify-content:center;padding-top:54px}.toc{position:sticky;top:92px;align-self:start;display:grid;gap:10px}.toc span{margin-bottom:4px;color:var(--green);font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.toc a{color:var(--muted)!important;text-decoration:none!important;font-size:12px;line-height:1.45}.toc a:hover{color:var(--ink)!important}.prose section+section{margin-top:42px}.prose h2{margin:0 0 12px;font-family:var(--font-display);font-size:31px;line-height:1.05;letter-spacing:-.045em}.prose p{margin:0 0 12px;color:var(--ink-2);font-size:16px;line-height:1.8}.article-cta{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-top:50px;padding:28px;border:1px solid var(--line);border-radius:18px;background:var(--surface)}.article-cta h2{margin:6px 0;font-family:var(--font-display);font-size:26px;letter-spacing:-.04em}.article-cta p{margin:0;color:var(--muted);font-size:12px}.not-found{text-align:center;padding:100px 20px}.not-found h1{font-family:var(--font-display);font-size:44px;letter-spacing:-.05em}.not-found p{color:var(--muted);margin-bottom:24px}@media(max-width:800px){.article-head{padding:48px 0 28px}.article-layout{grid-template-columns:1fr;gap:30px}.toc{position:static;padding:15px;border:1px solid var(--line);border-radius:14px;background:var(--surface)}.toc a{display:inline-block;margin-right:12px}.article-cta{display:block}.article-cta .trove-button{margin-top:18px;width:100%}}@media(max-width:560px){.article-page{padding-top:16px}.article-head h1{font-size:43px}.article-head>p{font-size:16px}.cover img{height:300px;border-radius:18px}.meta{display:grid;gap:8px}.prose h2{font-size:27px}.prose p{font-size:15px}}
</style>
