import { Hono } from 'hono'
import { getCookie } from 'hono/cookie'
import { authRepository } from '../auth/repository'
import { audit } from '../security/audit'
import { canAccessAdmin, canManageGuides, canManageTours, canManageUsers, deleteGuide, getDashboard, getDashboardTrends, getGuide, getUserDetails, getBookingDetails, listGuides, listUsers, listBookings, listAuditEvents, saveGuide, updateUserAdmin, listAdminTours, getAdminTour, saveAdminTour, listAdminProviders, listPromotions, getPromotion, savePromotion, deletePromotion, listHomepageBlocks, getHomepageBlock, saveHomepageBlock, deleteHomepageBlock } from './service'

const SESSION_COOKIE = process.env.NODE_ENV === 'production' ? '__Host-trove_session' : 'trove_session'
async function activeUser(c:any){const id=getCookie(c,SESSION_COOKIE);if(!id)return null;const session=await authRepository.findSession(id);if(!session)return null;const user=await authRepository.findUserById(session.userId);return user??null}
function denied(c:any){return c.json({error:'FORBIDDEN'},403)}

export const adminRoutes = new Hono()
adminRoutes.use('*',async(c,next)=>{const user=await activeUser(c);if(!user||!canAccessAdmin(user.role))return c.json({error:'ADMIN_UNAUTHORIZED'},401);(c as any).set('adminUser',user);await next()})
adminRoutes.get('/me',c=>{const u=(c as any).get('adminUser') as any;return c.json({user:{id:u.id,firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}})})
adminRoutes.get('/dashboard',async c=>c.json(await getDashboard()))
adminRoutes.get('/dashboard/trends',async c=>c.json(await getDashboardTrends(Number(c.req.query('days')||14))))
adminRoutes.get('/users',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageUsers(u.role))return denied(c);const q=c.req.query();return c.json(await listUsers({search:q.search,status:q.status,role:q.role,page:q.page?Number(q.page):1,limit:q.limit?Number(q.limit):25}))})
adminRoutes.patch('/users/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageUsers(u.role))return denied(c);const body=await c.req.json().catch(()=>null) as any;if(body?.status&&!['active','suspended'].includes(body.status))return c.json({error:'INVALID_STATUS'},400);if(body?.role&&!['user','admin','manager','editor'].includes(body.role))return c.json({error:'INVALID_ROLE'},400);const item=await updateUserAdmin(c.req.param('id'),{status:body?.status,role:body?.role});if(!item)return c.json({error:'NOT_FOUND'},404);await audit({type:'ADMIN_USER_UPDATED' as never,userId:u.id,metadata:{targetUserId:item.id,changes:{status:body?.status,role:body?.role}}});return c.json({user:{id:item.id,firstName:item.firstName,lastName:item.lastName,email:item.email,phone:item.phone,status:item.status,role:item.role}})})
adminRoutes.get('/users/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageUsers(u.role))return denied(c);const item=await getUserDetails(c.req.param('id'));return item?c.json(item):c.json({error:'NOT_FOUND'},404)})
adminRoutes.get('/bookings/:id',async c=>{const item=await getBookingDetails(c.req.param('id'));return item?c.json(item):c.json({error:'NOT_FOUND'},404)})
adminRoutes.get('/bookings',async c=>{const q=c.req.query();return c.json(await listBookings({search:q.search,status:q.status,page:q.page?Number(q.page):1,limit:q.limit?Number(q.limit):25}))})
adminRoutes.get('/audit',async c=>c.json({items:await listAuditEvents(Number(c.req.query('limit')||100))}))
adminRoutes.get('/tours',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageTours(u.role))return denied(c);return c.json(await listAdminTours(c.req.query()))})
adminRoutes.get('/tours/:providerId/:offerId',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageTours(u.role))return denied(c);const item=await getAdminTour(c.req.param('providerId'),c.req.param('offerId'));return item?c.json(item):c.json({error:'NOT_FOUND'},404)})
adminRoutes.patch('/tours/:providerId/:offerId',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageTours(u.role))return denied(c);const body=await c.req.json().catch(()=>null) as any;if(!body||Object.keys(body).some(k=>!['isActive','isFeatured','titleOverride','descriptionOverride','badgeOverride','tagsOverride','adminNotes'].includes(k)))return c.json({error:'INVALID_INPUT'},400);if(body.tagsOverride!==undefined&&!Array.isArray(body.tagsOverride))return c.json({error:'INVALID_TAGS'},400);const item=await saveAdminTour({providerId:c.req.param('providerId'),offerId:c.req.param('offerId'),isActive:body.isActive,isFeatured:body.isFeatured,titleOverride:body.titleOverride,descriptionOverride:body.descriptionOverride,badgeOverride:body.badgeOverride,tagsOverride:body.tagsOverride,adminNotes:body.adminNotes,updatedBy:u.id});await audit({type:'ADMIN_TOUR_UPDATED' as never,userId:u.id,metadata:{providerId:c.req.param('providerId'),offerId:c.req.param('offerId')}});return c.json({item})})
adminRoutes.get('/providers',async c=>{const u=(c as any).get('adminUser') as any;if(!canAccessAdmin(u.role))return denied(c);return c.json({items:await listAdminProviders()})})
adminRoutes.get('/promotions',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);return c.json({items:await listPromotions()})})
adminRoutes.get('/promotions/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const item=await getPromotion(c.req.param('id'));return item?c.json({item}):c.json({error:'NOT_FOUND'},404)})
adminRoutes.post('/promotions',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const body=await c.req.json().catch(()=>null) as any;if(!body||typeof body.slug!=='string'||!['draft','published','archived'].includes(body.status)||!body.translations||typeof body.translations!=='object')return c.json({error:'INVALID_INPUT'},400);const item=await savePromotion({id:typeof body.id==='string'?body.id:undefined,slug:body.slug,status:body.status,imageUrl:body.imageUrl,badge:body.badge,startsAt:body.startsAt,endsAt:body.endsAt,priority:Number(body.priority||0),translations:body.translations,userId:u.id});return c.json({item})})
adminRoutes.delete('/promotions/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const ok=await deletePromotion(c.req.param('id'));return ok?c.json({ok:true}):c.json({error:'NOT_FOUND'},404)})
adminRoutes.get('/homepage-blocks',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);return c.json({items:await listHomepageBlocks()})})
adminRoutes.get('/homepage-blocks/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const item=await getHomepageBlock(c.req.param('id'));return item?c.json({item}):c.json({error:'NOT_FOUND'},404)})
adminRoutes.post('/homepage-blocks',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const body=await c.req.json().catch(()=>null) as any;if(!body||typeof body.blockType!=='string'||!['draft','published','archived'].includes(body.status))return c.json({error:'INVALID_INPUT'},400);const item=await saveHomepageBlock({id:typeof body.id==='string'?body.id:undefined,blockType:body.blockType,status:body.status,sortOrder:Number(body.sortOrder||0),locale:body.locale||'all',title:body.title,subtitle:body.subtitle,data:body.data||{},userId:u.id});return c.json({item})})
adminRoutes.delete('/homepage-blocks/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const ok=await deleteHomepageBlock(c.req.param('id'));return ok?c.json({ok:true}):c.json({error:'NOT_FOUND'},404)})
adminRoutes.get('/guides',async c=>{const u=(c as any).get('adminUser') as any;if(!canAccessAdmin(u.role))return denied(c);return c.json({items:await listGuides()})})
adminRoutes.get('/guides/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canAccessAdmin(u.role))return denied(c);const item=await getGuide(c.req.param('id'));return item?c.json({item}):c.json({error:'NOT_FOUND'},404)})
adminRoutes.post('/guides',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const body=await c.req.json().catch(()=>null) as any;if(!body||typeof body.title!=='string'||typeof body.slug!=='string'||typeof body.content!=='string'||!['draft','published','archived'].includes(body.status))return c.json({error:'INVALID_INPUT'},400);const item=await saveGuide({id:typeof body.id==='string'?body.id:undefined,slug:body.slug,title:body.title,excerpt:body.excerpt,coverUrl:body.coverUrl,content:body.content,status:body.status,authorId:u.id,seoTitle:body.seoTitle,seoDescription:body.seoDescription});await audit({type:'ADMIN_GUIDE_SAVED' as never,userId:u.id,metadata:{guideId:item.id}});return c.json({item})})
adminRoutes.delete('/guides/:id',async c=>{const u=(c as any).get('adminUser') as any;if(!canManageGuides(u.role))return denied(c);const ok=await deleteGuide(c.req.param('id'));if(ok)await audit({type:'ADMIN_GUIDE_DELETED' as never,userId:u.id,metadata:{guideId:c.req.param('id')}});return ok?c.json({ok:true}):c.json({error:'NOT_FOUND'},404)})
