<template>
  <MarketingList title="Автоматизации" eyebrow="AUTOMATIONS">
    <div class="page">
      <section class="hero"><div><span class="eyebrow">EVENT → CONDITION → DELAY → ACTION</span><h2>Маркетинг работает по событиям</h2><p>Сценарии запускаются от поведения пользователя, ждут заданную задержку и выполняют только разрешённые действия.</p></div><button @click="runDue" :disabled="running">{{ running ? 'Запускаю…' : 'Запустить due сейчас' }}</button></section>
      <section class="flows"><article v-for="flow in flows" :key="flow.id" class="flow"><div class="status" :class="flow.status">{{ flow.status }}</div><div class="main"><div class="title"><h3>{{ flow.name }}</h3><span>delay {{ flow.trigger.delayMinutes }} min</span></div><div class="pipeline"><b>{{ flow.trigger.event }}</b><i>→</i><b v-if="flow.conditions.length">{{ flow.conditions.length }} condition</b><b v-else>always</b><i>→</i><b>{{ flow.actions.length }} action</b></div><p>{{ describe(flow) }}</p></div><select :value="flow.status" @change="changeStatus(flow.id, ($event.target as HTMLSelectElement).value)"><option value="active">ACTIVE</option><option value="paused">PAUSED</option><option value="draft">DRAFT</option></select></article></section>
      <section class="executions"><div class="sectionHead"><div><span class="eyebrow">EXECUTION LOG</span><h2>Последние выполнения</h2></div><button class="ghost" @click="load">Обновить</button></div><div v-if="!executions.length" class="empty">Пока нет запланированных выполнений.</div><div v-for="item in executions" :key="item.id" class="execution"><span class="dot" :class="item.status"></span><div><b>{{ item.status }}</b><p>{{ item.automationId }} · {{ item.runAt }}</p></div><span class="actor">{{ item.userId || item.sessionId || 'anonymous' }}</span></div></section>
      <div class="guard"><strong>Контроль</strong><p>Автоматизация не тратит рекламный бюджет. Внешние email/Telegram-доставки пока только ставятся в очередь и не маскируются под реально отправленные сообщения.</p></div>
    </div>
  </MarketingList>
</template>
<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: ['admin'] })
const apiClient = useApi()
const flows = ref<any[]>([]); const executions = ref<any[]>([]); const running = ref(false)
const api = (path:string, options:any={}) => apiClient(`/api${path}`, options)
const load = async () => { const [a,e] = await Promise.all([api('/marketing/automations'),api('/marketing/automations/executions?limit=30')]); flows.value=a.items; executions.value=e.items }
const runDue = async () => { running.value=true; try { await api('/marketing/automations/run-due',{method:'POST'}); await load() } finally { running.value=false } }
const changeStatus = async (id:string,status:string) => { await api(`/marketing/automations/${id}`,{method:'PATCH',body:{status}}); await load() }
const describe=(flow:any)=>`${flow.trigger.event} → ${flow.conditions.length ? 'проверить условия' : 'без дополнительных условий'} → ${flow.actions.map((x:any)=>x.type === 'marketing_message' ? x.channel : 'campaign draft').join(', ')}`
onMounted(load)
</script>
<style scoped lang="scss">
.page{display:grid;gap:12px}.hero,.executions,.guard,.flow{background:#fff;border:1px solid #dfe5e1;border-radius:16px}.hero{padding:24px;display:flex;justify-content:space-between;gap:20px;align-items:end}.eyebrow{font:800 10px Inter,sans-serif;letter-spacing:.11em;color:#668177}.hero h2,.sectionHead h2{font:800 25px/1.15 Manrope;margin:8px 0}.hero p,.guard p,.flow p,.execution p{font:14px/1.55 Inter;color:#697770;margin:0}.hero button,.ghost{border:0;border-radius:9px;padding:11px 14px;font:800 12px Inter;cursor:pointer}.hero button{background:#17382c;color:#fff}.flows{display:grid;gap:10px}.flow{padding:18px;display:flex;align-items:center;gap:18px}.status{font:800 9px Inter;letter-spacing:.08em;padding:7px 8px;border-radius:7px;background:#edf2ef;color:#66736c}.status.active{background:#eaf7f0;color:#188054}.status.paused{background:#fff5df;color:#9b6b12}.main{flex:1}.title{display:flex;align-items:center;gap:10px}.title h3{margin:0;font:800 16px Manrope}.title span{font:600 10px Inter;color:#89958f}.pipeline{display:flex;align-items:center;gap:8px;margin:10px 0}.pipeline b{font:800 10px Inter;background:#f1f5f2;padding:7px 8px;border-radius:6px}.pipeline i{font-style:normal;color:#8a9891}.flow select{border:1px solid #dbe3de;border-radius:8px;padding:8px;font:800 10px Inter;background:#fff}.executions{padding:20px}.sectionHead{display:flex;justify-content:space-between;align-items:center}.sectionHead h2{font-size:20px}.ghost{background:#f1f5f2;color:#355247}.execution{display:flex;align-items:center;gap:12px;padding:12px 0;border-top:1px solid #e8ece9}.dot{width:9px;height:9px;border-radius:50%;background:#9aa59f}.dot.completed{background:#2b9b68}.dot.scheduled{background:#d59b2d}.dot.failed{background:#c85656}.execution b{font:800 12px Inter}.execution p{font-size:11px}.actor{margin-left:auto;font:600 10px Inter;color:#89958f}.empty{padding:20px;color:#7b8781;font:13px Inter}.guard{padding:18px}.guard strong{font:800 13px Inter}@media(max-width:800px){.hero{display:grid}.flow{align-items:flex-start;flex-wrap:wrap}.flow select{margin-left:auto}.actor{display:none}}
</style>
