<template>
  <div>
    <div class="admin-page-head"><div><NuxtLink to="/admin/tours" class="back-link">← Все туры</NuxtLink><h1>{{ form.titleOverride || item?.offer?.title || 'Тур' }}</h1><p>{{ item?.offer?.provider }} · {{ item?.offer?.providerOfferId }}</p></div><div class="actions"><span class="pill" :class="form.isActive ? 'success' : 'warn'">{{ form.isActive ? 'Активен' : 'Скрыт' }}</span><button class="btn primary" :disabled="saving" @click="save">{{ saving ? 'Сохраняем…' : 'Сохранить' }}</button></div></div>
    <div v-if="item" class="tour-admin-grid">
      <section class="admin-card preview-card"><img :src="item.offer.image" alt=""><div class="preview-body"><span class="pill">{{ item.offer.provider }}</span><h2>{{ form.titleOverride || item.offer.title }}</h2><p>{{ item.offer.hotel }} · {{ item.offer.city }}, {{ item.offer.destination }}</p><div class="preview-price">{{ money(item.offer.price) }} {{ item.offer.currency }}</div><div class="tour-meta"><span>★ {{ item.offer.rating }}</span><span>{{ item.offer.duration }} дней</span><span>{{ item.offer.meal }}</span></div></div></section>
      <section class="admin-card"><h2>Управление витриной</h2><div class="field"><label>Название в Trove</label><input v-model="form.titleOverride" class="input" placeholder="Оставить исходное название"></div><div class="field"><label>Описание</label><textarea v-model="form.descriptionOverride" class="textarea small" placeholder="Короткое описание"></textarea></div><div class="field"><label>Badge</label><select v-model="form.badgeOverride" class="select"><option value="">Без badge</option><option value="recommended">Recommended</option><option value="hot">Hot</option><option value="sale">Sale</option><option value="new">New</option></select></div><div class="field"><label>Теги, через запятую</label><input v-model="tagsText" class="input" placeholder="Пляж, All Inclusive, Прямой рейс"></div><label class="check"><input v-model="form.isActive" type="checkbox"> Показывать в каталоге</label><label class="check"><input v-model="form.isFeatured" type="checkbox"> Выделять как featured</label><div class="field"><label>Заметка для команды</label><textarea v-model="form.adminNotes" class="textarea small" placeholder="Например: проверить комиссию"></textarea></div></section>
      <section class="admin-card source-card"><h2>Источник</h2><dl><dt>Provider</dt><dd>{{ item.offer.provider }}</dd><dt>Offer ID</dt><dd>{{ item.offer.providerOfferId }}</dd><dt>Направление</dt><dd>{{ item.offer.destination }}</dd><dt>Вылет</dt><dd>{{ item.offer.departure }} · {{ item.offer.departureDate }}</dd><dt>Номер</dt><dd>{{ item.offer.room }}</dd><dt>Обновлено</dt><dd>{{ item.offer.priceUpdatedAt }}</dd></dl></section>
    </div>
    <div v-else class="admin-card empty">Предложение не найдено или поставщик недоступен.</div>
  </div>
</template>
<script setup lang="ts">
definePageMeta({layout:'admin',middleware:'admin'})
const route=useRoute(); const api=useApi(); const saving=ref(false); const item=ref<any>(null)
const form=reactive({isActive:true,isFeatured:false,titleOverride:'',descriptionOverride:'',badgeOverride:'',adminNotes:''}); const tagsText=ref('')
const load=async()=>{item.value=await api(`/api/admin/tours/${route.params.providerId}/${route.params.offerId}`); const a=item.value?.admin; if(a){Object.assign(form,{isActive:a.is_active!==false,isFeatured:Boolean(a.is_featured),titleOverride:a.title_override||'',descriptionOverride:a.description_override||'',badgeOverride:a.badge_override||'',adminNotes:a.admin_notes||''});tagsText.value=Array.isArray(a.tags_override)?a.tags_override.join(', '):''}}
await load()
const save=async()=>{saving.value=true;try{await api(`/api/admin/tours/${route.params.providerId}/${route.params.offerId}`,{method:'PATCH',body:{isActive:form.isActive,isFeatured:form.isFeatured,titleOverride:form.titleOverride||null,descriptionOverride:form.descriptionOverride||null,badgeOverride:form.badgeOverride||null,tagsOverride:tagsText.value.split(',').map(v=>v.trim()).filter(Boolean),adminNotes:form.adminNotes||null}});await load()}finally{saving.value=false}}
const money=(v:number)=>new Intl.NumberFormat('ru-RU').format(Number(v||0))
</script>
<style scoped>
.back-link{display:inline-block;color:#687386;text-decoration:none;font-size:13px;margin-bottom:10px}.tour-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.preview-card{padding:0;overflow:hidden}.preview-card>img{display:block;width:100%;height:260px;object-fit:cover}.preview-body{padding:22px}.preview-body h2{margin:14px 0 8px;font-size:24px}.preview-body p{color:#778296}.preview-price{font-size:26px;font-weight:800;margin:22px 0 12px}.tour-meta{display:flex;gap:16px;color:#687386;font-size:13px}.admin-card h2{font-size:17px;margin:0 0 20px}.small{min-height:100px}.check{display:flex;gap:9px;align-items:center;margin:14px 0;font-size:13px}.source-card{grid-column:1/-1}.source-card dl{display:grid;grid-template-columns:150px 1fr;gap:10px;margin:0}.source-card dt{color:#8792a3;font-size:12px}.source-card dd{margin:0;font-size:13px}@media(max-width:800px){.tour-admin-grid{grid-template-columns:1fr}.source-card{grid-column:auto}}
</style>
